# Generated by Django 4.2.4 on 2023-08-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_video_captions_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='caption_file',
            field=models.FileField(null=True, upload_to='subtitles'),
        ),
    ]
