# Generated by Django 4.2.4 on 2023-08-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_video_caption_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='captions',
        ),
        migrations.AlterField(
            model_name='video',
            name='caption_file',
            field=models.FileField(default='h.txt', upload_to=''),
            preserve_default=False,
        ),
    ]
